### ISSUE TITLE
Fix deadzones on controller 

### ISSUE THREAD

**Issue by steph-lheureux** [CabrilloRoboticsClub/cabrillo_rov_2023#118]
Robot does not respond when making fast "rolling" movements with the joystick. possibly an issue with axis scaling

**Comment by steph-lheureux** [comment]
Seems like this may not be an issue, potentially jut a problem with the servos. The transitions are smooth in rviz

**Comment by OrionOth** [comment]
Specifically, the current provided by the test platform is too low for the old servos we are using to all move at once.

**Comment by cTurtle98** [comment]
well also the servos are just partially broken
