### ISSUE TITLE
missing boot config in ansible

### ISSUE THREAD

**Issue by cTurtle98** [CabrilloRoboticsClub/cabrillo_rov_2023#125]
@OrionOth reported to me there is missing lines in the boot config to make everything work after running the ansible on a blank sd card.

I need to know what they are so I can implement them

**Comment by OrionOth** [comment]
wait why did this automatically close wtf they arent even related

**Comment by cTurtle98** [comment]
Because you said the only thing I was missing was the i2c params that I added in the above pr
