### ISSUE TITLE
[ROV] Set logic tube camera servo default to angle 0

### ISSUE THREAD

**Issue by OrionOth** [CabrilloRoboticsClub/cabrillo_rov_2023#130]

**Comment by cTurtle98** [comment]
Do you mean 90 degrees?

**Comment by DerVerrater** [comment]
Are we sure we want the vehicle to home it's actuators on startup? If anything is obstructing them, we could damage components by forcing an angle setting.

**Comment by cTurtle98** [comment]
https://github.com/CabrilloRoboticsClub/cabrillo_rov_2023/blob/ba10f64dc2225e003da1889db74c4018266869bd/src/seahawk_rov/seahawk_rov/logic_tube_servo.py#L52

we already do this btw @OrionOth
