### ISSUE TITLE
ansible enable auto login on deck

### ISSUE THREAD

**Issue by cTurtle98** [CabrilloRoboticsClub/cabrillo_rov_2023#135]
enable auto login for the ubuntu user with ansible on deck

**Comment by OrionOth** [comment]
It _looks_ like this is done through the GDM config, which can be found under `/etc/gdm3/custom.conf`, specifically these lines under the `[daemon]` heading
```ini
[daemon]
...
AutomaticLoginEnable=True
AutomaticLogin=ubuntu
```
