### ISSUE TITLE
[alt impl] Use RCL Context shutdown for halting ROV

### ISSUE THREAD

**Issue by DerVerrater** [CabrilloRoboticsClub/cabrillo_rov_2023#146]
# Goal

Use ROS's Context objects to handle shutdown events. This is an alternative way to do what the finalizers (`__del__`) do in #145.

# Context objects

The ROS Core Library offers Context objects (`rclpy.Context` for us), and these can register callbacks to be run on-shutdown. Ciaran experimented with doing so in the changes for issue #145, but dropped it as they didn't seem to be doing anything.

I think the Context manager needs to be shutdown manually, just like we're doing with the Executor. A (brief) read of the rclpy source doesn't suggest that calling either `Context.shutdown()` or `Executor.shutdown()` will invoke the other. It seems like they must each be run, but I'm not real sure right now.

# Action Items

- Write functions to halt the ROV.
    - Resetting things to some home position (like claws) shouldn't be done here -- that's an initialization task.
- Hook up functions to a context manager.
- Call the context's `shutdown()` method as one of the actions performed during exception handling.

Keep in mind that `finally:` blocks are run last, and long-running exception handlers can delay the time between an exception occurring and the thrusters halting. I don't think we're in danger of that here, but it's worth remembering. Something something safety first.

**Comment by cTurtle98** [comment]
https://docs.ros2.org/foxy/api/rclpy/api/init_shutdown.html#rclpy.shutdown

from what I can tell `rclpy.shutdown()` (which is run by `rclpy.try_shutdown`) is supposed to shutdown the default context

im confused wat
