### ISSUE TITLE
Implement Monitoring on the ROV

### ISSUE THREAD

**Issue by mike-matera** [CabrilloRoboticsClub/cabrillo_rov_2023#167]
This feature will export some important Linux-level metrics from the ROV so they can be monitored by the software development team:

1. CPU usage (%)
2. Load average
3. Memory usage (%) 
4. CPU temperature 
5. Network bandwidth 

These metrics will make it easy for developers to see when their work has overloaded the RPi, which could be the source of bugs. 

## Getting Started

Start with the example publisher code here: 

https://ros2-industrial-workshop.readthedocs.io/en/latest/_source/basics/ROS2-Simple-Publisher-Subscriber.html

Update the `MinimalPublisher` class to use the functions of the `psutil` Python library which makes the getting the metrics a snap in Python. The documentation of `psutil` is here: 

https://psutil.readthedocs.io/en/latest/

This is a good project for someone who wants to learn ROS.

**Comment by liamgilligan** [comment]
Wrote some code on a branch (apologies to who it may concern, no clue if I'm following the standards for the branch), (0a445498fd5e0885697eb92f64865f050530ce30), let me know how this works or if you want me to change anything.
