### ISSUE TITLE
Create throttle curves

### ISSUE THREAD

**Issue by steph-lheureux** [CabrilloRoboticsClub/cabrillo_rov_2023#191]
Throttle curves are used in drone piloting to change the relationship between the position of the stick and the amount of throttle produced.  This can allow for increased control of the vehicle in certain situations.

Currently, the code has a linear ratio between the position of the sticks on the xbox to the amount of thrust the motors produce. For example if the stick is at 50 percent, 50 percent of the max throttle is produced by the motors
![standard](https://github.com/CabrilloRoboticsClub/cabrillo_rov_2023/assets/96219204/5a8e9c15-01f0-4cc1-8190-cf20239791f8)

A throttle curve remaps the stick input to throttle values along a certain curve.  A throttle curve like the one below  remaps low stick input to even lower throttle values allowing for more control at reduced speeds
![throttlecurve](https://github.com/CabrilloRoboticsClub/cabrillo_rov_2023/assets/96219204/59c1e813-75bc-452e-b897-5c96cc81f94a)

Write an implementation for throttle curves on the ROV. This should be done on the input_xbox_one node by remapping each `joy_node` sick input to a curve before adding these values to the twist message. Something like the following
```py
twist_msg.linear.x  = thrt_crv(controller["linear_x"] )
```
In addition add functionality for choosing different throttle curves. These will be selected using keyboard presses, `0`, `1`, `2`, etc. These values should be taken from the `throttle_curve_choice` ROS parameter (which is remotely updated by the `keyboard` node. For now, do not worry about the exact curves to use, these will need to be tested in the water before we know what works best. Just start with the basic implementation

**Comment by tinymassi** [comment]
This was finished and merged to main yeehaw

**Comment by steph-lheureux** [comment]
I was working on the dashboard and found an bug with the throttle curve implementation. I created a branch, [thrt-crv-bug](https://github.com/CabrilloRoboticsClub/cabrillo_rov_2023/tree/thrt-crv-bug) with a `self.get_logger().info()` which should help you in finding the bug as well. This is another really weird bug because we looked at the ros graph utility and curves seemed to be happening?? Is there anything which you think could have changed @tinymassi

**Comment by steph-lheureux** [comment]
Update: The previous comment seems to have resolved itself? Maybe I was not running it properly. For now lets assume this is not a problem
