### ISSUE TITLE
Drive Kinematics

### ISSUE THREAD

**Issue by OrionOth** [CabrilloRoboticsClub/cabrillo_rov_2023#26]
- [x] Controller Handling
  - [x] Calculate Input Scaling for Twist
    - [x] algorithmically
    - [x] implement properly
- [x] Motor Kinematics
  - [x] basic
  - [x] scale each factor based on all factors or smth
  - [x] #46
- [x] #44

**Comment by cTurtle98** [comment]
for reference
![image](https://user-images.githubusercontent.com/24465356/218289124-639a4a1b-cb58-406e-ae7a-eec1516be245.png)

**Comment by OrionOth** [comment]
#41

**Comment by OrionOth** [comment]
Closing because the code-splitting is now out-of-scope of this. The basic kinematics are DONE.
