### ISSUE TITLE
ROV Cameras

### ISSUE THREAD

**Issue by OrionOth** [CabrilloRoboticsClub/cabrillo_rov_2023#27]
There are currently issues with video4linux, the camera drivers we are using. Namely, `/dev/video0` can't be opened.
This issue exists outside of ROS, and the camera simply does not work at all.
```sh
$ sudo dmesg | grep -i camera
[  321.449064] bcm2835-v4l2-0: Failed enabling camera, ret -2
[  321.454741] bcm2835-v4l2-0: Failed to enable camera
```

**Comment by cTurtle98** [comment]
publishing of the rov is already implemented with the submodule mike added

**Comment by OrionOth** [comment]
```py
[h264_cam_node-1] [video4linux2,v4l2 @ 0xaaab02718e10] Cannot find a proper format for codec 'h264' (id 27), pixel format 'none' (id -1)
[h264_cam_node-1] [ERROR] [1678314685.129901946] [front_camera]: Could not open the v4l device: /dev/video0
[h264_cam_node-1] terminate called after throwing an instance of 'std::runtime_error'
[h264_cam_node-1]   what():  Could not open the v4l device
```

**Comment by OrionOth** [comment]
Status update: We need new cameras. The Arducam B0180 IMX219 we are using takes too much memory and only gives an uncompressed image stream that we can't handle properly on our 4gb Pi.

**Comment by cTurtle98** [comment]
status update. we bought rpi cam v3 and they arent supported on ubuntu yet.

we bought rpi cam v2
