### ISSUE TITLE
enable cameras on ubuntu on raspberry pi with ansible

### ISSUE THREAD

**Issue by cTurtle98** [CabrilloRoboticsClub/cabrillo_rov_2023#28]
the imx219 camera module does not work out of the box

steps are needed to enable it

ubuntu 22.04 on pi 4

**Comment by cTurtle98** [comment]
this needs to happen before #27 can happen

**Comment by cTurtle98** [comment]
adding
```
dtoverlay=imx219
```
to `/boot/config.txt` is how you enable the camera on raspbian

but that file doesnt exist on ubuntu 22.04 on pi

**Comment by OrionOth** [comment]
I did this on the test platform to `/boot/firmware/config.txt`, but it's still not working right. I'm now getting these errors:
```py
[h264_cam_node-1] [video4linux2,v4l2 @ 0xaaab02718e10] Cannot find a proper format for codec 'h264' (id 27), pixel format 'none' (id -1)
[h264_cam_node-1] [ERROR] [1678314685.129901946] [front_camera]: Could not open the v4l device: /dev/video0
[h264_cam_node-1] terminate called after throwing an instance of 'std::runtime_error'
[h264_cam_node-1]   what():  Could not open the v4l device
```

**Comment by OrionOth** [comment]
Update: per #27 we are switching to use different cameras, so this may be changing.

**Comment by cTurtle98** [comment]
pi cam v2 requires below in boot config to work
```
camera_auto_detect=0
display_auto_detect=1
start_x=1
```

@mike-matera whats the startx about

**Comment by OrionOth** [comment]
I'm not sure what the `start_x` line means in the boot config file, but the command `startx` starts the X display server with a default config file. I think it likely the two are related somehow, though commonly X is started via the init system (`systemd`/`init`).
