### ISSUE TITLE
implement BME280 sensor in ROS

### ISSUE THREAD

**Issue by cTurtle98** [CabrilloRoboticsClub/cabrillo_rov_2023#3]
https://www.adafruit.com/product/2652
we will have two of this device.
one in the logic tube, and one in the thrust box.

implement a publisher in ros for the sensor data

sensor library docs:
https://learn.adafruit.com/adafruit-bme280-humidity-barometric-pressure-temperature-sensor-breakout/python-circuitpython-test

ros docs for writing publisher:
http://docs.ros.org/en/humble/Tutorials/Beginner-Client-Libraries/Writing-A-Simple-Py-Publisher-And-Subscriber.html

**Comment by cTurtle98** [comment]
https://vscode.dev/github/CabrilloRoboticsClub/cabrillo_rov_2023/tree/3-implement-bme280-sensor-in-ros
open this branch is vs code web

**Comment by DerVerrater** [comment]
ROS2 Python API docs.
https://docs.ros2.org/foxy/api/rclpy/api/node.html

**Comment by cTurtle98** [comment]
working in branch i2c_proxy-to-ros-node
