### ISSUE TITLE
Create GitHub Issue Templates

### ISSUE THREAD

**Issue by OrionOth** [CabrilloRoboticsClub/cabrillo_rov_2023#49]
We should probably create issue templates for:
- [ ] Bug reports
  - [ ] Failing test results
- [ ] Conversation Topics
- [ ] Pull Requests
- [ ] ...

This requires outlines for each template and implementation by repo owner probably? See #48 for what I think is a good example of a "Failing Test Results" template.
Something many people like to do is add emojis to increase color and ease of reading in the templates. Maybe this can be considered?

**Comment by cTurtle98** [comment]
ooh, this would be good
