### ISSUE TITLE
[seahawk_deck] controller interface for claws

### ISSUE THREAD

**Issue by cTurtle98** [CabrilloRoboticsClub/cabrillo_rov_2023#54]
decide how to control claws with the xbox controller and write the publisher for it

dependent of #44

**Comment by OrionOth** [comment]
The publisher is working, we just need to decide on a control scheme.

**Comment by MKVollmer25** [comment]
Functionality is complete in the claw_control branch and I mapped it to the A button for testing. A pull request will be made once we can agree on exactly which button will be used.
