### ISSUE TITLE
[BUG] ROS coordinate frames do not match what we are using

### ISSUE THREAD

**Issue by OrionOth** [CabrilloRoboticsClub/cabrillo_rov_2023#93]
Pretty much all coordinate frames we are using do not comply with the standard ROS coordinate frames and it is causing _issues_.
We were basing our stuff off of [traditional underwater ROV convention](https://user-images.githubusercontent.com/24465356/218289124-639a4a1b-cb58-406e-ae7a-eec1516be245.png), but that is NOT [what ROS uses](https://github.com/siemens/ros-sharp/wiki/img/Dev_ROS_Unity_Coordinate_Systems.PNG).

**Comment by MKVollmer25** [comment]
Fix checklist

- [x] Linear X
- [x] Linear Y
- [x] Linear Z
- [x] Angular Y
- [x] Angular Z
