### ISSUE TITLE
configure robot_uptime to launch robot on boot

### ISSUE THREAD

**Issue by cTurtle98** [CabrilloRoboticsClub/cabrillo_rov_2023#99]
create systemd files to start robot code at boot

**Comment by OrionOth** [comment]
https://roboticsbackend.com/make-ros-launch-start-on-boot-with-robot_upstart/
https://index.ros.org/p/robot_upstart/#humble

**Comment by DerVerrater** [comment]
https://en.m.wikipedia.org/wiki/Upstart_(software)

Upstart has been in maintenance mode for almost 10 years. We're not getting a copy of Ubuntu that has it instead of Systemd, and we're not doing to dual-stack init systems -- especially a dead one.

**Comment by MKVollmer25** [comment]
Added the service to seahawk-rov-spare.local. The manual launch seems to be working, but the launch fails when done by the robot_upstart service. See #122.
